name: 'Identify Contributors'
description: 'Kudos Basic Identify Contributors'
inputs:
  path:  # starting point to look
    description: 'Path of repo'
    required: true
    default: '.'
outputs:
  contributors: 
    description: 'All contributors'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
